# Configuration script for Travis-CI
language: python
dist: xenial
python:
  - 2.7
  - 3.6
  - 3.7
matrix:
  include:
    - python: 2.7
      name: "Flake8"
      install:  pip install -U flake8
      script: flake8 src setup.py
      after_success:
install:
  - pip install -U pip setuptools zope.testrunner
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"
script:
  - coverage run -m zope.testrunner --test-path=src --auto-color
after_success:
  - coveralls
notifications:
  email: false
cache: pip
